// import './globals.css'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';
import AppHeader from '@/components/app.header';
import AppTable from '@/components/app.table';
import AppFooter from '@/components/app.footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppHeader></AppHeader>
        
        <div className='container'>
          {children}

          <AppTable></AppTable>
        </div>


        <AppFooter></AppFooter>
      </body>
    </html>
  )
}
